services:
  mysql:
    container_name: sikggu-mysql
    image: 'mysql:8.0'
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=sikggu1234
      - MYSQL_DATABASE=sikggu
    volumes:
      - sikggu-data:/var/lib/mysql

volumes:
  sikggu-data:
